name: arm64-qt

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: git --no-pager show HEAD
    - name: install libs
      run: |
        ls
        ls "C:\Program Files (x86)"
        ls "C:\Program Files (x86)\Microsoft Visual Studio"
        ls "C:\Program Files (x86)\Microsoft Visual Studio\2019"
        ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\VC"
        ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\VC\Auxiliary"
        ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\VC\Auxiliary\Build"
        ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\VC\Auxiliary\Build\vcvarsall.bat"
        ./build_qt.bat
